// <auto-generated />
using ControleFinanceiro.Infra.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControleFinanceiro.Infra.Migrations
{
    [DbContext(typeof(ControleFinanceiroContext))]
    partial class ControleFinanceiroContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ControleFinanceiro.Domain.Models.Categoria", b =>
                {
                    b.Property<int>("CatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cat_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CatId"));

                    b.Property<string>("CatDescricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("cat_descricao");

                    b.Property<int>("CatFinalidade")
                        .HasColumnType("int")
                        .HasColumnName("cat_finalidade");

                    b.HasKey("CatId")
                        .HasName("PK__Categori__DD5DDDBDB4C6B17A");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("ControleFinanceiro.Domain.Models.Pessoa", b =>
                {
                    b.Property<int>("PesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("pes_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PesId"));

                    b.Property<int>("PesIdade")
                        .HasColumnType("int")
                        .HasColumnName("pes_idade");

                    b.Property<string>("PesNome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("pes_nome");

                    b.HasKey("PesId")
                        .HasName("PK__Pessoas__410B66F8CB6BFB3B");

                    b.ToTable("Pessoas");
                });

            modelBuilder.Entity("ControleFinanceiro.Domain.Models.Transaco", b =>
                {
                    b.Property<int>("TraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("tra_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TraId"));

                    b.Property<int>("CatId")
                        .HasColumnType("int")
                        .HasColumnName("cat_id");

                    b.Property<int>("PesId")
                        .HasColumnType("int")
                        .HasColumnName("pes_id");

                    b.Property<string>("TraDescricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("tra_descricao");

                    b.Property<int>("TraTipo")
                        .HasColumnType("int")
                        .HasColumnName("tra_tipo");

                    b.Property<decimal>("TraValor")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("tra_valor");

                    b.HasKey("TraId")
                        .HasName("PK__Transaco__9E078C13C03A993F");

                    b.HasIndex("CatId");

                    b.HasIndex("PesId");

                    b.ToTable("Transacoes");
                });

            modelBuilder.Entity("ControleFinanceiro.Domain.Models.Transaco", b =>
                {
                    b.HasOne("ControleFinanceiro.Domain.Models.Categoria", "Cat")
                        .WithMany("Transacos")
                        .HasForeignKey("CatId")
                        .IsRequired()
                        .HasConstraintName("FK_Transacoes_Categorias");

                    b.HasOne("ControleFinanceiro.Domain.Models.Pessoa", "Pes")
                        .WithMany("Transacos")
                        .HasForeignKey("PesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Transacoes_Pessoas");

                    b.Navigation("Cat");

                    b.Navigation("Pes");
                });

            modelBuilder.Entity("ControleFinanceiro.Domain.Models.Categoria", b =>
                {
                    b.Navigation("Transacos");
                });

            modelBuilder.Entity("ControleFinanceiro.Domain.Models.Pessoa", b =>
                {
                    b.Navigation("Transacos");
                });
#pragma warning restore 612, 618
        }
    }
}
